name: Github Workflow for Postman

on:
  schedule:
  - cron: "0 13 * * 1"
  push:
    branches:
    - master

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Hooks, build postman collections
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          apiKey: ${{ secrets.postmanApiKey }}
          collection: 16486240-5b7143b0-1821-4440-9200-9f9df7cb1d76
      - name: Run Postman Collections
        run: echo ${{ steps.run-newman.outputs.summary }}