name: Github Workflow for Postman

on:
  push:
    branches:
    - master

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install newman reporter
        run: |
          npm install -g newman
      - name: Run Postman Collections
        run: |
          newman run ./postman_collection.json