name: Github Workflow for Postman

on:
  schedule:
  - cron: "0 13 * * 1"
  push:
    branches:
    - master

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Hooks, build postman
        id: run-newman
        uses: anthonyvscode/newman-action@v1.1
        with:
          apiKey: ${{ secrets.POSTMANAPIKEY }}
          collection: 16486240-5b7143b0-1821-4440-9200-9f9df7cb1d76
          reporters: cli

      - name: Run Postman Collections
        run: echo ${{ steps.run-newman.outputs.summary }}